spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql=info

file.uploadPath=${FILE_UPLOAD_PATH:/tmp/tourgo/uploads}
